#! /bin/bash
#
#set -x
# Author: Dimitrios Dimitrakos mail@dimitrios.de
#
#
### BEGIN INIT INFO
# Provides:          vdrconvert
# Required-Start:    
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: VDR Universalconverter based on vdrsync from Doc 
# Description:       
### END INIT INFO

# VDR config
VDRSCRIPTDIR="/usr/lib/vdr/scripts"
VDRUSER="vdruser"
[ -r /etc/default/vdr ] && . /etc/default/vdr

# Check for missing binaries/scripts (stale symlinks should not happen)
VDRCONVERTDIR="$(dirname $VDRSCRIPTDIR)/vdrconvert"
VDR2DVDSYNC=$VDRCONVERTDIR/bin/vdrconvert.sh
test -x $VDR2DVDSYNC || exit 5

# Source LSB init functions
# providing start_daemon, killproc, pidofproc, 
# log_success_msg, log_failure_msg and log_warning_msg.
# This is currently not used by UnitedLinux based distributions and
# not needed for init scripts for UnitedLinux only. If it is used,
# the functions from rc.status should not be sourced or used.
#. /lib/lsb/init-functions

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_status -s     display "skipped" and exit with status 3
#      rc_status -u     display "unused" and exit with status 3
#      rc_failed        set local and overall rc status to failed
#      rc_failed <num>  set local and overall rc status to <num>
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
#      rc_active	checks whether a service is activated by symlinks
#      rc_splash arg    sets the boot splash screen to arg (if active)
#. /etc/rc.status

# Reset status of this service
# rc_reset

# Return values acc. to LSB for all commands but status:
# 0	  - success
# 1       - generic or unspecified error
# 2       - invalid or excess argument(s)
# 3       - unimplemented feature (e.g. "reload")
# 4       - user had insufficient privileges
# 5       - program is not installed
# 6       - program is not configured
# 7       - program is not running
# 8--199  - reserved (8--99 LSB, 100--149 distrib, 150--199 appl)
# 
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signaling is not supported) are
# considered a success.

CONV_USER=$VDRUSER
LOGFILE=/dev/null

# Activate only for Debug
#LOGFILE=/var/log/vdrconvert/vdrconvert.log

case "$1" in
    start)
	run=`ps -aef|grep "vdrconvert.sh"|grep -v grep|wc -l`	
	if [ $run -eq 0 ]
	then
	    echo -n "Starting VDRCONVERT "
	    su - $CONV_USER -c "(cd $VDRCONVERTDIR;./bin/vdrconvert.sh)" > $LOGFILE 2>&1 &
	else
	    echo -n "VDRCONVERT already running"
	fi
	;;
    stop)
	echo -n "Shutting down VDRCONVERT"
        ps -aef|grep vdrconvert|grep -v grep|awk '{print($2)}'|sort -n|xargs kill -n 9 >/dev/null 2>&1
	# rc_status -v
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac
# rc_exit
